### ISSUE TITLE
403 Client Error: Forbidden for url: https://bgp.tools/as/12389

### ISSUE THREAD

**Issue by strasharo** [SharkyRawr/asnban#2]
Is there any workaround for this exception?

```
python3 asnban.py --ufw --asn 12389
Traceback (most recent call last):
  File "/tmp/asnban/asnban.py", line 66, in <module>
    prefixes = bgptools.query_prefixes(args.asn)
  File "/tmp/asnban/providers/bgptools.py", line 13, in query_prefixes
    r.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://bgp.tools/as/12389
```
Works fine from browser though.

**Comment by SharkyRawr** [comment]
I pushed d057deefea1f9e8a7e240413917c30275e073bc2 which should hopefully fix this error. :)

**Comment by strasharo** [comment]
Yep, it works now, thanks a lot @SharkyRawr . :)
